# Generated by Django 4.2.1 on 2023-05-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_link', models.CharField(blank=True, max_length=100000, null=True)),
                ('name', models.CharField(blank=True, max_length=100000, null=True)),
            ],
        ),
    ]
